---
title: "Testing Programming Assignment 2"

---

First, I see to it that the directory I am working with is the the one that my GitHub directory is pointed at in my local computer. 

## upon checking it is not currently at so, I set my directory using
> getwd()
[1] "/Users/lapuk/Data_Science/datasciencescoursera"

## I set my working directory to where it is.
> setwd("~/Documents/GitHub/ProgrammingAssignment2/")

## recheck again if the directory is correct
> getwd()
[1] "/Users/lapuk/Documents/GitHub/ProgrammingAssignment2" 

## I loaded my source file 
> source("cachematrix.R")

## TESTING MY ASSIGNMENT
## I input values to my "test_matrix" variable using the function that was giving in the assignment. 
> test_matrix <- makeCacheMatrix(matrix(4:7, 2, 2))

## Testing if values input to my test_matrix 
## Remember the $get is from the function to call
> test_matrix$get()
     [,1] [,2]
[1,]    4    6
[2,]    5    7
## values 4, 5, 6, 7 are place on a 2X2 matrix as declared. 

> test_matrix$getInv()
NULL

## x$getmean() is defined again in the sample function given in the assignment. 

> cacheSolve(test_matrix)
     [,1] [,2]
[1,] -3.5    3
[2,]  2.5   -2

## Opps! Something is wrong here!
## play() 
## reviewing assignment function now.  :)

## HOW TO DELETE OR CLEAR YOUR RAM.
## I have come up with so many junk in my memory and that is why when testing, I get to have a lot
## of garbage error. I came with a site (https://stackoverflow.com/questions/11579765/how-to-clean-up-memory-not-need-to-restart-my-pc)
## You can clear your RAM without restarting and it make sure that all your variables are clear. 
## Try checking on ls()
## rm(list = ls())
## .rs.restartR()
## This helps a lot. As to why I am getting a lot of garbage a while ago while testing my assignment. :)

## nxt()

> cacheSolve(test_matrix)
Getting cached data - Inverted Matrix
     [,1] [,2]
[1,] -3.5    3
[2,]  2.5   -2

> test_matrix$getInv()
    [,1] [,2]
[1,] -3.5    3
[2,]  2.5   -2

## As per checking online, http://matrix.reshish.com/inverCalculation.php
	  B1	B2
1	-3.5	 3
2	 2.5	-2

## yelds to the same result.